# Filtering and Sorting Data

### Step 1. Import the necessary libraries

In [2]:
import pandas as pd

### Step 2. Import the dataset *chipotle.tsv*

In [3]:
chipo=pd.read_csv("chipotle.tsv",sep="\t")

### Step 3. Assign it to a variable called chipo.

In [4]:
chipo.head()

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98

### Step 4. How many products cost more than $10.00? 

Use `str` attribute to remove the $ sign and convert the column to proper numeric type data before filtering.

In [5]:
prices = [float(value[1 : -1]) for value in chipo.item_price]
chipo.item_price = prices
chipo_filtered = chipo.drop_duplicates(['item_name','quantity'])
chipo_one_prod = chipo_filtered[chipo_filtered.quantity == 1]
chipo_one_prod[chipo_one_prod['item_price']>10].item_name.nunique()

12

In [6]:
chipo.dtypes

order_id                int64
quantity                int64
item_name              object
choice_description     object
item_price            float64
dtype: object

### Step 5. What is the price of each item? 

print a data frame with only two columns `item_name` and `item_price`

In [7]:
chipo[(chipo['item_name'] == 'Chicken Bowl') & (chipo['quantity'] == 1)]

,order_id,quantity,item_name,choice_description,item_price
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",10.98
13,7,1,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
19,10,1,Chicken Bowl,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",8.75
26,13,1,Chicken Bowl,"[Roasted Chili Corn Salsa (Medium), [Pinto Bea...",8.49
42,20,1,Chicken Bowl,"[Roasted Chili Corn Salsa, [Rice, Black Beans,...",11.25
76,34,1,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",8.75
78,34,1,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",8.75
99,44,1,Chicken Bowl,"[Tomatillo Red Chili Salsa, [Rice, Fajita Vege...",8.75
110,49,1,Chicken Bowl,"[Tomatillo Red Chili Salsa, [Rice, Black Beans...",8.75
123,54,1,Chicken Bowl,"[Fresh Tomato Salsa, [Guacamole, Cheese, Sour ...",11.25
138,62,1,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Fajita Vegetables,...",11.25
140,63,1,Chicken Bowl,"[Tomatillo Green Chili Salsa, [Rice, Sour Crea...",11.25
142,64,1,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
160,73,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Black Beans, Rice...",8.49
176,79,1,Chicken Bowl,"[Roasted Chili Corn Salsa (Medium), [Black Bea...",10.98
182,82,1,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",8.75
193,86,1,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Cheese, Sour Cream]]",8.75
199,89,1,Chicken Bowl,"[[Roasted Chili Corn Salsa (Medium), Tomatillo...",10.98
206,92,1,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Cheese, Lettuce]]",8.75
209,93,1,Chicken Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",11.25
211,93,1,Chicken Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",11.25
218,96,1,Chicken Bowl,"[Tomatillo Green Chili Salsa, [Rice, Black Bea...",8.75
220,97,1,Chicken Bowl,"[Roasted Chili Corn Salsa, [Rice, Black Beans,...",8.75
224,98,1,Chicken Bowl,"[Tomatillo Green Chili Salsa, [Rice, Pinto Bea...",8.75
231,102,1,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",8.75
252,110,1,Chicken Bowl,"[Tomatillo Red Chili Salsa, [Rice, Cheese, Let...",8.75
257,111,1,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Cheese]]",8.75
284,124,1,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Cheese, Sour Cream]]",8.75
290,126,1,Chicken Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",11.25
291,127,1,Chicken Bowl,"[Tomatillo Green Chili Salsa, [Rice, Sour Crea...",11.25
...,...,...,...,...,...
4443,1771,1,Chicken Bowl,"[Tomatillo Green Chili Salsa, [Rice, Pinto Bea...",8.75
4444,1771,1,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",8.75
4465,1779,1,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Cheese]]",8.75
4481,1786,1,Chicken Bowl,"[Fresh Tomato Salsa, Rice]",8.75
4483,1786,1,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Pinto Beans, Chees...",11.25
4484,1786,1,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
4486,1786,1,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",11.25
4488,1786,1,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",8.75
4495,1788,1,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Pinto Beans, Sour ...",11.25
4498,1789,1,Chicken Bowl,"[Tomatillo Green Chili Salsa, [Fajita Vegetabl...",11.25
4506,1792,1,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Cheese, Sour Cream...",11.25
4511,1794,1,Chicken Bowl,"[Roasted Chili Corn Salsa, [Rice, Fajita Veget...",8.75
4532,1802,1,Chicken Bowl,"[Roasted Chili Corn Salsa, [Rice, Black Beans,...",8.75
4537,1804,1,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",8.75
4540,1805,1,Chicken Bowl,"[Tomatillo Green Chili Salsa, [Fajita Vegetabl...",11.25
4553,1810,1,Chicken Bowl,"[Roasted Chili Corn Salsa, [Black Beans, Sour ...",11.25
4555,1811,1,Chicken Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",8.75
4564,1815,1,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
4574,1819,1,Chicken Bowl,"[Roasted Chili Corn Salsa, [Rice, Cheese, Lett...",8.75
4576,1820,1,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Cheese, Sour Cream...",11.25
4581,1822,1,Chicken Bowl,"[Tomatillo Red Chili Salsa, [Rice, Black Beans...",8.75
4583,1823,1,Chicken Bowl,"[Tomatillo Green Chili Salsa, [Rice, Black Bea...",8.75
4586,1824,1,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",11.25
4587,1824,1,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",11.25
4589,1825,1,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",11.25
4590,1825,1,Chicken Bowl,"[Roasted Chili Corn Salsa, [Rice, Black Beans,...",11.25
4591,1825,1,Chicken Bowl,"[Tomatillo Red Chili Salsa, [Rice, Black Beans...",8.75
4595,1826,1,Chicken Bowl,"[Tomatillo Green Chili Salsa, [Rice, Black Bea...",8.75
4599,1827,1,Chicken Bowl,"[Roasted Chili Corn Salsa, [Cheese, Lettuce]]",8.75
4604,1828,1,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",8.75

### Step 6. Sort by the name of the item

In [8]:
chipo.sort_values(by = "item_name")

,order_id,quantity,item_name,choice_description,item_price
3389,1360,2,6 Pack Soft Drink,[Diet Coke],12.98
341,148,1,6 Pack Soft Drink,[Diet Coke],6.49
1849,749,1,6 Pack Soft Drink,[Coke],6.49
1860,754,1,6 Pack Soft Drink,[Diet Coke],6.49
2713,1076,1,6 Pack Soft Drink,[Coke],6.49
3422,1373,1,6 Pack Soft Drink,[Coke],6.49
553,230,1,6 Pack Soft Drink,[Diet Coke],6.49
1916,774,1,6 Pack Soft Drink,[Diet Coke],6.49
1922,776,1,6 Pack Soft Drink,[Coke],6.49
1937,784,1,6 Pack Soft Drink,[Diet Coke],6.49
3836,1537,1,6 Pack Soft Drink,[Coke],6.49
298,129,1,6 Pack Soft Drink,[Sprite],6.49
1976,798,1,6 Pack Soft Drink,[Diet Coke],6.49
1167,481,1,6 Pack Soft Drink,[Coke],6.49
3875,1554,1,6 Pack Soft Drink,[Diet Coke],6.49
1124,465,1,6 Pack Soft Drink,[Coke],6.49
3886,1558,1,6 Pack Soft Drink,[Diet Coke],6.49
2108,849,1,6 Pack Soft Drink,[Coke],6.49
3010,1196,1,6 Pack Soft Drink,[Diet Coke],6.49
4535,1803,1,6 Pack Soft Drink,[Lemonade],6.49
4169,1664,1,6 Pack Soft Drink,[Diet Coke],6.49
4174,1666,1,6 Pack Soft Drink,[Coke],6.49
4527,1800,1,6 Pack Soft Drink,[Diet Coke],6.49
4522,1798,1,6 Pack Soft Drink,[Diet Coke],6.49
3806,1525,1,6 Pack Soft Drink,[Sprite],6.49
2389,949,1,6 Pack Soft Drink,[Coke],6.49
3132,1248,1,6 Pack Soft Drink,[Diet Coke],6.49
3141,1253,1,6 Pack Soft Drink,[Lemonade],6.49
639,264,1,6 Pack Soft Drink,[Diet Coke],6.49
1026,422,1,6 Pack Soft Drink,[Sprite],6.49
...,...,...,...,...,...
2996,1192,1,Veggie Salad,"[Roasted Chili Corn Salsa (Medium), [Black Bea...",8.49
3163,1263,1,Veggie Salad,"[[Fresh Tomato Salsa (Mild), Roasted Chili Cor...",8.49
4084,1635,1,Veggie Salad,"[[Fresh Tomato Salsa (Mild), Roasted Chili Cor...",8.49
1694,686,1,Veggie Salad,"[[Fresh Tomato Salsa (Mild), Roasted Chili Cor...",8.49
2756,1094,1,Veggie Salad,"[[Tomatillo-Green Chili Salsa (Medium), Roaste...",8.49
4201,1677,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Black...",11.25
1884,760,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
455,195,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
3223,1289,1,Veggie Salad Bowl,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.25
2223,896,1,Veggie Salad Bowl,"[Roasted Chili Corn Salsa, Fajita Vegetables]",8.75
2269,913,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",8.75
4541,1805,1,Veggie Salad Bowl,"[Tomatillo Green Chili Salsa, [Fajita Vegetabl...",8.75
3293,1321,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",8.75
186,83,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
960,394,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",8.75
1316,536,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",8.75
2156,869,1,Veggie Salad Bowl,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.25
4261,1700,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
295,128,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",11.25
4573,1818,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",8.75
2683,1066,1,Veggie Salad Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",8.75
496,207,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Rice, Lettuce, Guacamole...",11.25
4109,1646,1,Veggie Salad Bowl,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.25
738,304,1,Veggie Soft Tacos,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.25
3889,1559,2,Veggie Soft Tacos,"[Fresh Tomato Salsa (Mild), [Black Beans, Rice...",16.98
2384,948,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",8.75
781,322,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Black Beans, Cheese, Sou...",8.75
2851,1132,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa (Medium), [Black Bea...",8.49
1699,688,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
1395,567,1,Veggie Soft Tacos,"[Fresh Tomato Salsa (Mild), [Pinto Beans, Rice...",8.49

### Step 7. What was the quantity of the most expensive item ordered?

In [9]:
chipo.sort_values(by = "item_price", ascending = False).head(1)

,order_id,quantity,item_name,choice_description,item_price
3598,1443,15,Chips and Fresh Tomato Salsa,NaN,44.25

### Step 8. How many times were a Veggie Salad Bowl ordered?

In [10]:
chipo_salad = chipo[chipo.item_name == "Veggie Salad Bowl"]

len(chipo_salad)

18

### Step 9. How many times people orderd more than one Canned Soda?

In [11]:
chipo_drink_steak_bowl = chipo[(chipo.item_name == "Canned Soda") & (chipo.quantity > 1)]
len(chipo_drink_steak_bowl)

20